const dummyData = [
  {
    name: "Alice Johnson",
    login: "alice-j",
    avatar_url: "https://github.com/alice-j.png",
    ownerProfile: "https://github.com/alice-j",
    repoName: "Task Manager",
    description: "A productivity app for managing tasks efficiently.",
    languages: { JavaScript: 1213, NodeJS: 2324 },
    issuesCount: 3,
    contributorCount: 7,
    url: "https://github.com/alice-j/task-manager",
    issues_url: "https://github.com/alice-j/task-manager/issues",
  },
  {
    name: "Bob Smith",
    login: "bob-smith",
    avatar_url: "https://github.com/bob-smith.png",
    ownerProfile: "https://github.com/bob-smith",
    repoName: "Weather App",
    description: "A weather forecasting web app using OpenWeather API.",
    languages: { VueJS: 1500, ExpressJS: 1200 },
    issuesCount: 5,
    contributorCount: 4,
    url: "https://github.com/bob-smith/weather-app",
    issues_url: "https://github.com/bob-smith/weather-app/issues",
  },
  {
    name: "Charlie Green",
    login: "charlie-g",
    avatar_url: "https://github.com/charlie-g.png",
    ownerProfile: "https://github.com/charlie-g",
    repoName: "Expense Tracker",
    description: "Track your daily expenses and manage budgets efficiently.",
    languages: { ReactJS: 1800, Firebase: 1000 },
    issuesCount: 2,
    contributorCount: 5,
    url: "https://github.com/charlie-g/expense-tracker",
    issues_url: "https://github.com/charlie-g/expense-tracker/issues",
  },
  {
    name: "David Lee",
    login: "david-lee",
    avatar_url: "https://github.com/david-lee.png",
    ownerProfile: "https://github.com/david-lee",
    repoName: "E-Commerce Platform",
    description: "A full-stack e-commerce platform with Stripe integration.",
    languages: { NextJS: 2500, MongoDB: 1900 },
    issuesCount: 8,
    contributorCount: 12,
    url: "https://github.com/david-lee/ecommerce-platform",
    issues_url: "https://github.com/david-lee/ecommerce-platform/issues",
  },
  {
    name: "Emma Davis",
    login: "emma-d",
    avatar_url: "https://github.com/emma-d.png",
    ownerProfile: "https://github.com/emma-d",
    repoName: "Portfolio Builder",
    description: "A tool to generate a professional portfolio in minutes.",
    languages: { ReactJS: 2000, TailwindCSS: 1200 },
    issuesCount: 6,
    contributorCount: 9,
    url: "https://github.com/emma-d/portfolio-builder",
    issues_url: "https://github.com/emma-d/portfolio-builder/issues",
  },
  {
    name: "Michael King",
    login: "michael-k",
    avatar_url: "https://github.com/michael-k.png",
    ownerProfile: "https://github.com/michael-k",
    repoName: "Travel Planner",
    description: "A travel itinerary planner with maps and recommendations.",
    languages: { Angular: 2300, Firebase: 1400 },
    issuesCount: 5,
    contributorCount: 8,
    url: "https://github.com/michael-k/travel-planner",
    issues_url: "https://github.com/michael-k/travel-planner/issues",
  },
];

export default dummyData;
